#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ClusterClass"})
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: tkg-vsphere-default-v1.1.0-extended
spec:
  variables:
  - name: sysctl
    required: false
    schema:
      openAPIV3Schema:
        type: string
  patches:
  - name: sysctl
    definitions:
      - selector:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          matchResources:
            machineDeploymentClass:
              names:
              - tkg-worker
        jsonPatches:
          - op: add
            path: /spec/template/spec/preKubeadmCommands/-
            value: sysctl -w vm.nr_hugepages=0
          - op: add
            path: /spec/template/spec/preKubeadmCommands/-
            value: sysctl -w vm.max_map_count=262144
